In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("Ola.csv")
data.head()

C:\Users\dhruv\AppData\Local\Temp\ipykernel_20240\1607815406.py:1: DtypeWarning: Columns (1,4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("Ola.csv")

,ID,vendor+AF8-id,pickup+AF8-loc,drop+AF8-loc,driver+AF8-tip,mta+AF8-tax,distance,pickup+AF8-time,drop+AF8-time,num+AF8-passengers,toll+AF8-amount,payment+AF8-method,rate+AF8-code,stored+AF8-flag,extra+AF8-charges,improvement+AF8-charge,total+AF8-amount
0,0,1,170.0,233.0,1.83,0.5,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1.0,0.0,1.0,1.0,N,1,0.3,9.13
1,1,2,151.0,243.0,3.56,0.5,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1.0,0.0,1.0,1.0,N,1,0.3,21.36
2,2,2,68.0,90.0,1.5,0.5,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,2.0,0.0,1.0,1.0,N,0,0.3,8.8
3,3,2,142.0,234.0,1.5,0.5,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,1.0,0.0,1.0,1.0,N,0,0.3,14.8
4,4,2,238.0,238.0,0,0.5,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,6.0,0.0,2.0,1.0,N,0,0.3,4.8

In [3]:
data.shape

(1048575, 17)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 17 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   ID                      1048575 non-null  int64
 1   vendor+AF8-id           1048575 non-null  object
 2   pickup+AF8-loc          1048574 non-null  float64
 3   drop+AF8-loc            1048574 non-null  float64
 4   driver+AF8-tip          1048573 non-null  object
 5   mta+AF8-tax             1048574 non-null  object
 6   distance                1048574 non-null  float64
 7   pickup+AF8-time         1048574 non-null  object
 8   drop+AF8-time           1048574 non-null  object
 9   num+AF8-passengers      1048574 non-null  float64
 10  toll+AF8-amount         1048573 non-null  object
 11  payment+AF8-method      1048574 non-null  float64
 12  rate+AF8-code           1048574 non-null  float64
 13  stored+AF8-flag         1048574 non-null  object
 14  extra+AF8-charges       1048574 non-null  object
 15  improvement+AF8-charge  1048573 non-null  object
 16  total+AF8-amount        1048573 non-null  object
dtypes: float64(6), int64(1), object(10)
memory usage: 136.0+ MB

In [5]:
data.isnull().sum()

ID                        0
vendor+AF8-id             0
pickup+AF8-loc            1
drop+AF8-loc              1
driver+AF8-tip            2
mta+AF8-tax               1
distance                  1
pickup+AF8-time           1
drop+AF8-time             1
num+AF8-passengers        1
toll+AF8-amount           2
payment+AF8-method        1
rate+AF8-code             1
stored+AF8-flag           1
extra+AF8-charges         1
improvement+AF8-charge    2
total+AF8-amount          2
dtype: int64

In [6]:
col_to_drop=['mta+AF8-tax','num+AF8-passengers','toll+AF8-amount','rate+AF8-code','stored+AF8-flag','improvement+AF8-charge','payment+AF8-method','driver+AF8-tip']

data=data.drop(col_to_drop, axis=1)

In [7]:
data=data.rename(columns={
    'vendor+AF8-id':'Vendor ID',
    'pickup+AF8-loc': 'Pick_up Loc',
    'drop+AF8-loc': 'Drop Loc',
    'distance':'Distance',
    'pickup+AF8-time':'Pick_up Time',
    'drop+AF8-time':'Drop Time',
    'extra+AF8-charges':'Extra Charges',
    'total+AF8-amount':'Total Amount'
    
})

In [8]:
data['Extra Charges'].unique()

array(['1', '0', '0.5', '4.5', '+AC0-0.5', '+AC0-1', '1.8', '0.8', '0.05',
       '+AC0-4.5', '6.5', '1.5', nan, '0.2', '0.1', '1.3'], dtype=object)

In [9]:
data.head()

,ID,Vendor ID,Pick_up Loc,Drop Loc,Distance,Pick_up Time,Drop Time,Extra Charges,Total Amount
0,0,1,170.0,233.0,0.70,04/04/2017 05:59:43 PM,04/04/2017 06:05:04 PM,1,9.13
1,1,2,151.0,243.0,4.64,04/03/2017 07:03:34 PM,04/03/2017 07:20:04 PM,1,21.36
2,2,2,68.0,90.0,1.29,04/03/2017 03:06:13 PM,04/03/2017 03:12:30 PM,0,8.8
3,3,2,142.0,234.0,2.74,04/04/2017 08:10:52 AM,04/04/2017 08:27:00 AM,0,14.8
4,4,2,238.0,238.0,0.45,04/05/2017 02:02:59 PM,04/05/2017 02:05:41 PM,0,4.8

In [10]:
data.isnull().sum()

ID               0
Vendor ID        0
Pick_up Loc      1
Drop Loc         1
Distance         1
Pick_up Time     1
Drop Time        1
Extra Charges    1
Total Amount     2
dtype: int64

In [11]:
data.shape

(1048575, 9)

In [12]:
data=data.dropna()

In [13]:
dup=data.duplicated()
dup.sum()
data=data.drop_duplicates()

In [14]:
data.shape

(1048573, 9)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1048573 entries, 0 to 1048574
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ID             1048573 non-null  int64
 1   Vendor ID      1048573 non-null  object
 2   Pick_up Loc    1048573 non-null  float64
 3   Drop Loc       1048573 non-null  float64
 4   Distance       1048573 non-null  float64
 5   Pick_up Time   1048573 non-null  object
 6   Drop Time      1048573 non-null  object
 7   Extra Charges  1048573 non-null  object
 8   Total Amount   1048573 non-null  object
dtypes: float64(3), int64(1), object(5)
memory usage: 80.0+ MB

In [16]:
data['Vendor ID']=data['Vendor ID'].astype(int)

In [17]:
data['Extra Charges'].unique()

array(['1', '0', '0.5', '4.5', '+AC0-0.5', '+AC0-1', '1.8', '0.8', '0.05',
       '+AC0-4.5', '6.5', '1.5', '0.2', '0.1', '1.3'], dtype=object)

In [18]:
data=data[data['Extra Charges']!='+AC0-0.5']
data=data[data['Extra Charges']!='+AC0-4.5']
data=data[data['Extra Charges']!= '+AC0-1']

In [19]:
data['Extra Charges']=data['Extra Charges'].astype(float)

In [20]:
data['Total Amount'].unique()

array(['9.13', '21.36', '8.8', ..., '58.4', '64.94', '128.75'],
      dtype=object)

In [21]:
data=data[data['Total Amount']!='+AC0-5.3']
data=data[data['Total Amount']!='+AC0-4.3']
data=data[data['Total Amount']!='+AC0-4.8']
data=data[data['Total Amount']!='+AC0-5.8']
data=data[data['Total Amount']!='+AC0-6.3']
data=data[data['Total Amount']!='+AC0-3.3']
data=data[data['Total Amount']!='+AC0-52.8']
data=data[data['Total Amount']!='+AC0-6.8']

In [22]:
data = data[~data['Total Amount'].astype(str).str.contains('+AC0-', na=False, regex=False)]

In [23]:
data['Total Amount']=data['Total Amount'].astype(float)

In [24]:
data = data.reset_index(drop=True)

In [25]:
data.shape

(1048052, 9)

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048052 entries, 0 to 1048051
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ID             1048052 non-null  int64
 1   Vendor ID      1048052 non-null  int64
 2   Pick_up Loc    1048052 non-null  float64
 3   Drop Loc       1048052 non-null  float64
 4   Distance       1048052 non-null  float64
 5   Pick_up Time   1048052 non-null  object
 6   Drop Time      1048052 non-null  object
 7   Extra Charges  1048052 non-null  float64
 8   Total Amount   1048052 non-null  float64
dtypes: float64(5), int64(2), object(2)
memory usage: 72.0+ MB

In [27]:
data['Pick_up Time'] = pd.to_datetime(data['Pick_up Time'], format='%m/%d/%Y %I:%M:%S %p')
data['Drop Time'] = pd.to_datetime(data['Drop Time'], format='%m/%d/%Y %I:%M:%S %p')

In [28]:
print(data['Pick_up Time'].dtype)

datetime64[ns]

In [31]:
data.shape

(1048052, 9)

**Feature Extraction**

In [34]:
data['Trip Duration (min)']=((data['Drop Time']-data['Pick_up Time']).dt.total_seconds()/60).astype(int)

In [35]:
data['Hour of Day']=data['Pick_up Time'].dt.hour

In [36]:
data['Day of Week']=data['Pick_up Time'].dt.day_name()

In [37]:
data.head()

,ID,Vendor ID,Pick_up Loc,Drop Loc,Distance,Pick_up Time,Drop Time,Extra Charges,Total Amount,Trip Duration (min),Hour of Day,Day of Week
0,0,1,170.0,233.0,0.70,2017-04-04 17:59:43,2017-04-04 18:05:04,1.0,9.13,5,17,Tuesday
1,1,2,151.0,243.0,4.64,2017-04-03 19:03:34,2017-04-03 19:20:04,1.0,21.36,16,19,Monday
2,2,2,68.0,90.0,1.29,2017-04-03 15:06:13,2017-04-03 15:12:30,0.0,8.80,6,15,Monday
3,3,2,142.0,234.0,2.74,2017-04-04 08:10:52,2017-04-04 08:27:00,0.0,14.80,16,8,Tuesday
4,4,2,238.0,238.0,0.45,2017-04-05 14:02:59,2017-04-05 14:05:41,0.0,4.80,2,14,Wednesday

In [38]:
data.columns

Index(['ID', 'Vendor ID', 'Pick_up Loc', 'Drop Loc', 'Distance',
       'Pick_up Time', 'Drop Time', 'Extra Charges', 'Total Amount',
       'Trip Duration (min)', 'Hour of Day', 'Day of Week'],
      dtype='object')

In [39]:
data.to_csv("Cleaned_Data.csv",index=False)

In [40]:
#there are huge number of rows in it so it will create problems while making Dashboard so we are doing sampling to reduce it

In [45]:
sample_size = 10000

df_sampled = data.groupby('Hour of Day', group_keys=False).apply(lambda x: x.sample(frac=sample_size/len(data), random_state=42))

C:\Users\dhruv\AppData\Local\Temp\ipykernel_20240\3089428088.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sampled = data.groupby('Hour of Day', group_keys=False).apply(lambda x: x.sample(frac=sample_size/len(data), random_state=42))

In [46]:
df_sampled.shape

(9997, 12)

In [47]:
df_sampled.head()

,ID,Vendor ID,Pick_up Loc,Drop Loc,Distance,Pick_up Time,Drop Time,Extra Charges,Total Amount,Trip Duration (min),Hour of Day,Day of Week
184533,184629,1,87.0,260.0,8.40,2017-04-05 00:16:51,2017-04-05 00:36:36,0.5,26.80,19,0,Wednesday
282034,282174,2,68.0,162.0,2.67,2017-04-06 00:42:08,2017-04-06 00:55:56,0.5,15.96,13,0,Thursday
947857,948318,2,161.0,48.0,1.25,2017-04-05 00:14:04,2017-04-05 00:21:04,0.5,7.80,7,0,Wednesday
223958,224074,2,4.0,17.0,4.35,2017-04-04 00:33:10,2017-04-04 00:49:46,0.5,22.25,16,0,Tuesday
716135,716477,2,148.0,148.0,2.11,2017-04-07 00:33:19,2017-04-07 00:56:06,0.5,21.00,22,0,Friday

In [ ]:
# Say your data has:

# 10 lakh rows
# Hour 8 has 50,000 rows (5%)
# Hour 9 has 1,00,000 rows (10%
# If you ask for a 100,000-row sample (sample_size=100000), this line ensures:
# Hour 8 contributes ~5% of 100,000 → ~5,000 rows
# Hour 9 contributes ~10% of 100,000 → ~10,000 rows
# …and so on for all hours.

In [48]:
df_sampled.to_csv("Filtered_Data.csv", index=False)