**We have 5 datasets based on our need we will clean them one by one**

**Dataset 1 = Netflix movievs and TV shows**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data1=pd.read_csv("Netflix Movies and TV Shows Metadata/netflix_titles.csv")
data1.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
data1.shape

(8807, 12)

In [4]:
data1.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [5]:
data1['rating'].isnull().sum()

4

In [6]:
null = data1[data1['rating'].isnull()]
null

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [7]:
data1['type'].nunique()

2

In [8]:
data1['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [9]:
data1['listed_in'].unique()

array(['Documentaries', 'International TV Shows, TV Dramas, TV Mysteries',
       'Crime TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Reality TV',
       'International TV Shows, Romantic TV Shows, TV Comedies',
       'TV Dramas, TV Horror, TV Mysteries', 'Children & Family Movies',
       'Dramas, Independent Movies, International Movies',
       'British TV Shows, Reality TV', 'Comedies, Dramas',
       'Crime TV Shows, Docuseries, International TV Shows',
       'Dramas, International Movies',
       'Children & Family Movies, Comedies',
       'British TV Shows, Crime TV Shows, Docuseries',
       'TV Comedies, TV Dramas', 'Documentaries, International Movies',
       'Crime TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Thrillers',
       'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'International TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies',
       'Comedies, International Movies, Romantic Movies',
       'Docuseries, International TV Shows, Reality TV',
       'Comedies, International Movies, Music & Musicals', 'Comedies',
       'Horror Movies, Sci-Fi & Fantasy', 'TV Comedies',
       'British TV Shows, International TV Shows, TV Comedies',
       'International TV Shows, TV Dramas, TV Thrillers', "Kids' TV",
       'Dramas, International Movies, Thrillers',
       'Action & Adventure, Dramas, International Movies',
       "Kids' TV, TV Comedies", 'Action & Adventure, Dramas',
       "Kids' TV, TV Sci-Fi & Fantasy",
       'Action & Adventure, Classic Movies, Dramas',
       'Dramas, Horror Movies, Thrillers',
       'Action & Adventure, Horror Movies, Thrillers',
       'Action & Adventure', 'Dramas, Thrillers',
       'International TV Shows, TV Dramas',
       'International TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, Anime Features, International Movies',
       'Reality TV', 'Docuseries, International TV Shows',
       'Documentaries, International Movies, Sports Movies',
       'International TV Shows, Reality TV, Romantic TV Shows',
       'British TV Shows, Docuseries, International TV Shows',
       'Anime Series, International TV Shows',
       'Comedies, Dramas, International Movies',
       'Crime TV Shows, TV Comedies, TV Dramas',
       'Action & Adventure, Comedies, Dramas', "Anime Series, Kids' TV",
       'International Movies, Thrillers', "Kids' TV, Korean TV Shows",
       'Documentaries, Sports Movies', 'Sci-Fi & Fantasy, Thrillers',
       'Dramas, International Movies, Romantic Movies',
       'Documentaries, Music & Musicals',
       "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",
       "British TV Shows, Kids' TV", 'Docuseries, Science & Nature TV',
       'Children & Family Movies, Dramas',
       "Kids' TV, TV Dramas, Teen TV Shows",
       'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, International TV Shows, Spanish-Language TV Shows',
       'Dramas', 'Comedies, Romantic Movies', 'Dramas, Romantic Movies',
       'Comedies, Dramas, Independent Movies',
       'Crime TV Shows, TV Action & Adventure, TV Comedies',
       'Children & Family Movies, Music & Musicals',
       'Action & Adventure, Classic Movies, Cult Movies',
       'International TV Shows, TV Action & Adventure, TV Comedies',
       'Action & Adventure, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies', 'Classic Movies, Comedies, Dramas',
       'Comedies, Cult Movies', 'Comedies, Cult Movies, Music & Musicals',
       'Comedies, Music & Musicals', 'TV Shows',
       'Action & Adventure, International Movies',
       'Anime Series, International TV Shows, Teen TV Shows',
       'Action & Adventure, Children & Family Movies, Cult Movies',
       'Comedies, Dramas, Romantic Movies',
       'Comedies, Cult Movies, Sci-Fi & Fantasy',
       'Classic Movies, Dramas',
       'Action & Adventure, Children & Family Movies, Comedies',
       'Dramas, Faith & Spirituality', 'Documentaries, LGBTQ Movies',
       'Action & Adventure, Classic Movies', 'Docuseries',
       'International TV Shows, TV Comedies',
       'Dramas, Independent Movies',
       'Action & Adventure, Comedies, International Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Crime TV Shows, International TV Shows, TV Dramas',
       'Action & Adventure, Horror Movies, International Movies',
       'Comedies, International Movies, Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Music & Musicals',
       'Dramas, International Movies, Music & Musicals',
       'Horror Movies, International Movies', 'Reality TV, Teen TV Shows',
       'Crime TV Shows, TV Dramas, TV Mysteries',
       'International TV Shows, Reality TV',
       'International TV Shows, TV Comedies, TV Dramas',
       'Dramas, Independent Movies, Romantic Movies', 'Horror Movies',
       'Documentaries, LGBTQ Movies, Sports Movies',
       'Horror Movies, International Movies, Thrillers',
       'Action & Adventure, Anime Features',
       'TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy',
       'International TV Shows, Spanish-Language TV Shows, TV Comedies',
       'Children & Family Movies, Comedies, Music & Musicals',
       'Comedies, Independent Movies',
       'Anime Series, International TV Shows, Romantic TV Shows',
       'Classic Movies, Dramas, Independent Movies',
       'International TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'International TV Shows, TV Dramas, Teen TV Shows',
       'Stand-Up Comedy',
       'Action & Adventure, Anime Features, Children & Family Movies',
       'International TV Shows, Romantic TV Shows, TV Dramas',
       'International Movies, Music & Musicals',
       'TV Action & Adventure, TV Dramas, TV Mysteries',
       'Horror Movies, Independent Movies, International Movies',
       'Comedies, Cult Movies, International Movies',
       'Classic Movies, Dramas, International Movies', 'Movies',
       'Crime TV Shows, Docuseries',
       'Children & Family Movies, Comedies, Sci-Fi & Fantasy',
       'Anime Series, International TV Shows, TV Thrillers',
       'Action & Adventure, Horror Movies, Sci-Fi & Fantasy',
       'Classic Movies, Comedies, Cult Movies',
       'TV Dramas, Teen TV Shows',
       'Action & Adventure, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Comedies, Dramas',
       'Dramas, Sports Movies',
       'Action & Adventure, Dramas, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies, Cult Movies',
       'Dramas, Independent Movies, Thrillers',
       'TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Thrillers',
       'British TV Shows, International TV Shows, Reality TV',
       'TV Action & Adventure, TV Dramas, Teen TV Shows', 'Anime Series',
       'Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Crime TV Shows, International TV Shows, TV Comedies',
       'Stand-Up Comedy & Talk Shows, TV Comedies',
       'Classic & Cult TV, TV Action & Adventure, TV Dramas',
       'Children & Family Movies, Sports Movies',
       'TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Anime Series, Stand-Up Comedy & Talk Shows', 'TV Dramas',
       'Anime Features, Children & Family Movies, International Movies',
       'Classic & Cult TV, Crime TV Shows, International TV Shows',
       'Crime TV Shows, International TV Shows, Romantic TV Shows',
       'Horror Movies, LGBTQ Movies',
       'Action & Adventure, Dramas, Romantic Movies',
       'Documentaries, International Movies, Music & Musicals',
       'TV Comedies, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Comedies, Sports Movies',
       'Children & Family Movies, Dramas, International Movies',
       'Comedies, Documentaries, International Movies',
       'Romantic TV Shows, TV Dramas',
       'Anime Series, TV Horror, TV Thrillers',
       'International Movies, Romantic Movies',
       'TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy',
       "Kids' TV, Korean TV Shows, TV Comedies",
       'British TV Shows, Crime TV Shows, International TV Shows',
       'Crime TV Shows, TV Horror, TV Mysteries',
       'Docuseries, International TV Shows, Science & Nature TV',
       'British TV Shows, International TV Shows, TV Dramas',
       "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy",
       'International Movies, Romantic Movies, Thrillers',
       'Action & Adventure, Cult Movies, International Movies',
       'Action & Adventure, Comedies, Sci-Fi & Fantasy',
       "International TV Shows, Kids' TV, TV Mysteries",
       'Action & Adventure, Thrillers',
       'Dramas, Faith & Spirituality, International Movies',
       'Action & Adventure, Classic Movies, Comedies',
       'Action & Adventure, Comedies, Sports Movies',
       'Action & Adventure, Children & Family Movies, Classic Movies',
       'Action & Adventure, Children & Family Movies, Dramas',
       'Horror Movies, Thrillers', 'Action & Adventure, Romantic Movies',
       'Dramas, Romantic Movies, Sci-Fi & Fantasy',
       'Dramas, Music & Musicals, Romantic Movies',
       'Anime Series, Crime TV Shows, International TV Shows',
       'Reality TV, Romantic TV Shows',
       'International Movies, Music & Musicals, Romantic Movies',
       'Reality TV, TV Action & Adventure, TV Mysteries',
       'Crime TV Shows, TV Dramas',
       'International TV Shows, Reality TV, Spanish-Language TV Shows',
       'Crime TV Shows, TV Dramas, TV Thrillers',
       'British TV Shows, Docuseries',
       'International TV Shows, Korean TV Shows, TV Comedies',
       'Action & Adventure, Anime Features, Classic Movies',
       'TV Action & Adventure, TV Dramas, TV Horror',
       'Crime TV Shows, International TV Shows, TV Thrillers',
       'Anime Series, Crime TV Shows, TV Horror',
       'Anime Features, Documentaries', 'Comedies, Horror Movies',
       'International TV Shows, Spanish-Language TV Shows, Stand-Up Comedy & Talk Shows',
       'Children & Family Movies, Documentaries, International Movies',
       'Romantic TV Shows, TV Comedies, TV Dramas',
       'Dramas, Faith & Spirituality, Romantic Movies',
       'Dramas, Independent Movies, LGBTQ Movies',
       'Comedies, Independent Movies, LGBTQ Movies',
       'Action & Adventure, Cult Movies, Sci-Fi & Fantasy',
       'Cult Movies, Horror Movies',
       'Action & Adventure, Dramas, Sports Movies',
       'Anime Series, Romantic TV Shows, Teen TV Shows',
       'Dramas, International Movies, LGBTQ Movies',
       'Dramas, Romantic Movies, Thrillers',
       'Children & Family Movies, Dramas, Faith & Spirituality',
       'Dramas, International Movies, Sports Movies',
       'Action & Adventure, Horror Movies',
       'Documentaries, International Movies, LGBTQ Movies',
       'Dramas, Independent Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, International Movies',
       'Reality TV, TV Horror, TV Thrillers',
       'TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Sci-Fi & Fantasy',
       'Independent Movies, International Movies, Thrillers',
       'Independent Movies, Thrillers', 'Documentaries, Dramas',
       'Action & Adventure, Sports Movies',
       'Dramas, International Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, Romantic Movies',
       'Horror Movies, Romantic Movies, Sci-Fi & Fantasy',
       'International TV Shows, Stand-Up Comedy & Talk Shows',
       'Action & Adventure, Anime Features, Horror Movies',
       'Cult Movies, Dramas, Music & Musicals', 'TV Dramas, TV Thrillers',
       'Crime TV Shows, International TV Shows, Korean TV Shows',
       'TV Horror, TV Mysteries, TV Thrillers',
       'Comedies, Horror Movies, International Movies',
       'Crime TV Shows, Docuseries, TV Mysteries',
       'Comedies, International Movies, Sports Movies',
       'Classic Movies, Music & Musicals',
       'Reality TV, TV Comedies, TV Horror',
       'Children & Family Movies, Faith & Spirituality, Music & Musicals',
       'International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows',
       'Dramas, Music & Musicals',
       'Docuseries, Science & Nature TV, TV Action & Adventure',
       "British TV Shows, Kids' TV, TV Dramas",
       'International TV Shows, Korean TV Shows, Romantic TV Shows',
       'Horror Movies, Independent Movies',
       "Anime Series, Kids' TV, TV Action & Adventure",
       'Comedies, Dramas, Music & Musicals', 'TV Horror, Teen TV Shows',
       'Comedies, LGBTQ Movies, Thrillers',
       'Docuseries, Reality TV, Science & Nature TV',
       'Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'Romantic TV Shows, Teen TV Shows', 'TV Comedies, Teen TV Shows',
       'Romantic TV Shows, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Sci-Fi & Fantasy',
       'Romantic TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies, LGBTQ Movies',
       'Dramas, Sci-Fi & Fantasy', "Kids' TV, TV Thrillers",
       'TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy',
       'British TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Series, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, TV Comedies',
       'Comedies, Romantic Movies, Sports Movies',
       'TV Action & Adventure, TV Comedies, TV Dramas',
       'Children & Family Movies, Dramas, Sports Movies',
       'Action & Adventure, Dramas, Independent Movies',
       'Spanish-Language TV Shows, TV Dramas', 'Dramas, LGBTQ Movies',
       'TV Horror, TV Mysteries, TV Sci-Fi & Fantasy',
       'Action & Adventure, Dramas, Faith & Spirituality',
       'International TV Shows, TV Mysteries, TV Thrillers',
       'British TV Shows, Classic & Cult TV, International TV Shows',
       'Action & Adventure, Comedies, Independent Movies',
       'Music & Musicals', "British TV Shows, Kids' TV, TV Comedies",
       'Docuseries, Spanish-Language TV Shows',
       'Dramas, Independent Movies, Sports Movies',
       'TV Dramas, TV Mysteries, TV Thrillers',
       'Comedies, LGBTQ Movies, Music & Musicals',
       'International TV Shows, TV Action & Adventure, TV Mysteries',
       "Kids' TV, TV Comedies, Teen TV Shows",
       'International TV Shows, TV Dramas, TV Horror',
       'Comedies, International Movies, Thrillers',
       'Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Mysteries',
       'Children & Family Movies, Documentaries',
       'Music & Musicals, Romantic Movies', 'Romantic Movies',
       'Children & Family Movies, Classic Movies, Comedies',
       'TV Action & Adventure, TV Dramas',
       'Dramas, LGBTQ Movies, Romantic Movies',
       'Children & Family Movies, Comedies, Romantic Movies',
       'Comedies, Sports Movies', 'International Movies',
       'International TV Shows, Romantic TV Shows, TV Mysteries',
       'Stand-Up Comedy & Talk Shows',
       'Action & Adventure, International Movies, Romantic Movies',
       'Reality TV, TV Comedies',
       'Cult Movies, Dramas, International Movies', "Kids' TV, TV Dramas",
       'Crime TV Shows, International TV Shows, TV Mysteries',
       'Action & Adventure, Sci-Fi & Fantasy, Sports Movies',
       'TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers',
       'Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Docuseries, TV Sci-Fi & Fantasy',
       'Anime Features, International Movies',
       "British TV Shows, Classic & Cult TV, Kids' TV",
       'British TV Shows, Reality TV, Romantic TV Shows',
       'Documentaries, Faith & Spirituality, International Movies',
       "Kids' TV, Reality TV, TV Dramas", 'LGBTQ Movies, Thrillers',
       'TV Action & Adventure, TV Mysteries, TV Sci-Fi & Fantasy',
       'Reality TV, Science & Nature TV',
       "Kids' TV, TV Action & Adventure, TV Comedies",
       'International TV Shows, Romantic TV Shows, TV Action & Adventure',
       'Children & Family Movies, Dramas, Independent Movies',
       'Comedies, Music & Musicals, Romantic Movies',
       'International TV Shows, Korean TV Shows, Reality TV',
       'Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy',
       'Anime Features, Children & Family Movies',
       'Action & Adventure, International Movies, Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure, TV Dramas',
       'Classic & Cult TV, TV Action & Adventure, TV Horror',
       'International TV Shows, Korean TV Shows, TV Dramas',
       'International TV Shows, TV Action & Adventure, TV Horror',
       'Action & Adventure, Comedies, Romantic Movies',
       'International TV Shows, Korean TV Shows, TV Action & Adventure',
       "Classic & Cult TV, Kids' TV, TV Action & Adventure",
       'Anime Series, International TV Shows, TV Horror',
       'International TV Shows, Korean TV Shows, TV Horror',
       'Children & Family Movies, Comedies, International Movies',
       'International Movies, Sci-Fi & Fantasy',
       'International Movies, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Dramas, Romantic Movies',
       'Anime Series, Romantic TV Shows',
       'Comedies, Dramas, LGBTQ Movies',
       'British TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Science & Nature TV, TV Comedies',
       'International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies',
       'Children & Family Movies, Dramas, Music & Musicals',
       'Action & Adventure, Independent Movies, International Movies',
       'Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy',
       'Horror Movies, Independent Movies, Sci-Fi & Fantasy',
       'TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows',
       'Anime Features, International Movies, Sci-Fi & Fantasy',
       'Dramas, Independent Movies, Music & Musicals',
       "Kids' TV, TV Comedies, TV Dramas",
       'Children & Family Movies, Documentaries, Sports Movies',
       'Independent Movies, Sci-Fi & Fantasy, Thrillers',
       'Anime Features, Music & Musicals, Sci-Fi & Fantasy',
       'TV Comedies, TV Dramas, TV Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure',
       'Comedies, Faith & Spirituality, Romantic Movies',
       "Kids' TV, TV Action & Adventure",
       'Action & Adventure, Independent Movies',
       'International TV Shows, Reality TV, TV Comedies',
       'Docuseries, Reality TV, Teen TV Shows',
       'Crime TV Shows, International TV Shows, Reality TV',
       'Anime Series, Teen TV Shows',
       'Crime TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Features, Romantic Movies',
       'Horror Movies, Sci-Fi & Fantasy, Thrillers',
       'International TV Shows, TV Comedies, TV Sci-Fi & Fantasy',
       'International TV Shows, Romantic TV Shows',
       'Anime Features, Music & Musicals',
       'Anime Features, International Movies, Romantic Movies',
       'International TV Shows, Romantic TV Shows, Teen TV Shows',
       'Docuseries, Stand-Up Comedy & Talk Shows',
       'Horror Movies, Independent Movies, Thrillers',
       'TV Action & Adventure, TV Comedies, TV Horror',
       'Documentaries, Stand-Up Comedy',
       "Kids' TV, Spanish-Language TV Shows",
       "British TV Shows, Kids' TV, TV Thrillers",
       "Kids' TV, TV Action & Adventure, TV Dramas",
       'Anime Series, Crime TV Shows',
       'Dramas, Sci-Fi & Fantasy, Thrillers',
       'TV Comedies, TV Dramas, TV Horror',
       'Children & Family Movies, Comedies, LGBTQ Movies',
       'International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Docuseries, TV Dramas',
       'Horror Movies, International Movies, Romantic Movies',
       'Crime TV Shows, Docuseries, Science & Nature TV',
       'International Movies, Music & Musicals, Thrillers',
       "Kids' TV, Spanish-Language TV Shows, Teen TV Shows",

In [10]:
data1 = data1.dropna(subset=['rating'])
data1=data1.dropna(subset=['duration'])
data1=data1.drop(['date_added'], axis=1)
# data1=data1.dropna(['Nr'])
data1.shape

(8800, 11)

In [11]:
data1['director']=data1['director'].fillna('unknown')
data1['cast']=data1['cast'].fillna('unknown')
data1['country']=data1['country'].fillna('unknown')

In [12]:
data1.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [13]:
data1.to_csv("Netflix Movies and TV Shows[Cleaned].csv",index=False)

**Dataset 2 = Netflix Plans and prices**

In [14]:
data2=pd.read_csv("Netflix Plans & Prices/Netflix Prices.csv")
data2.head()
#| Country | Code | Currency (optional) | Mobile_USD | Basic_USD | Standard_USD | Premium_USD |

,Country,Code,Currency,Mobile,Basic,Standard,Premium,Conversion,Mobile_USD,Basic_USD,Standard_USD,Premium_USD
0,Viet Nam,VN,Vietnamese Dong,70000,180000.0,220000.0,260000.0,0.000043,3.01,7.740,9.460,11.180
1,Indonesia,ID,Indonesian Rupiah,54000,120000.0,153000.0,186000.0,0.000070,3.78,8.400,10.710,13.020
2,Colombia,CO,Colombian Peso,-,16900.0,26900.0,38900.0,0.000250,-,4.225,6.725,9.725
3,Korea�(South),KR,Korean Won,-,9500.0,13500.0,17000.0,0.000845,-,8.028,11.408,14.365
4,Chile,CL,Chilean Peso,-,5940.0,8320.0,10700.0,0.001175,-,6.980,9.776,12.572

In [15]:
data2.shape

(243, 12)

In [16]:
data2.columns

Index(['Country', 'Code', 'Currency', 'Mobile', 'Basic', 'Standard', 'Premium',
       'Conversion', 'Mobile_USD', 'Basic_USD', 'Standard_USD', 'Premium_USD'],
      dtype='object')

In [17]:
data2.isnull().sum()

Country         0
Code            1
Currency        0
Mobile          0
Basic           0
Standard        0
Premium         0
Conversion      0
Mobile_USD      0
Basic_USD       0
Standard_USD    0
Premium_USD     0
dtype: int64

In [18]:
col_to_drop = ['Currency', 'Mobile', 'Basic', 'Standard', 'Premium', 'Conversion']
data2 = data2.drop(col_to_drop, axis=1)

In [19]:
data2.isnull().sum()

Country         0
Code            1
Mobile_USD      0
Basic_USD       0
Standard_USD    0
Premium_USD     0
dtype: int64

In [20]:
data2=data2.dropna(subset='Code')

In [21]:
data2['Mobile_USD'].unique()

array(['3.01', '3.78', '-', '2.88', '1.403', '2.64', '1.956', '2.98',
       '2.958', '3.065', '4.039', '3.99', '4.59', '4.49'], dtype=object)

In [22]:
data2['Mobile_USD'] = data2['Mobile_USD'].replace('-', np.nan).astype(float)

In [23]:
data2['Mobile_USD']=data2['Mobile_USD'].fillna('Not Available')

In [24]:
data2.to_csv("Netflix Plans and Prices[Cleaned].csv", index=False)

**DataSet 3 = Netflix subscriber And Revenue overtime**

In [25]:
data3=pd.read_csv("Netflix Subscribers & Revenue Over Time/netflix_revenue_updated.csv")
data3.head()

,Date,Global Revenue,UCAN Streaming Revenue,EMEA Streaming Revenue,LATM Streaming Revenue,APAC Streaming Revenue,UCAN Members,EMEA Members,LATM Members,APAC Members,UCAN ARPU,EMEA ARPU,LATM ARPU,APAC ARPU,Netflix Streaming Memberships
0,31-03-2019,4520992000,2256851000,1233379000,630472000,319602000,66633000,42542000,27547000,12141000,11.45,10.23,7.84,9.37,148863000
1,30-06-2019,4923116000,2501199000,1319087000,677136000,349494000,66501000,44229000,27890000,12942000,12.52,10.13,8.14,9.29,151562000
2,30-09-2019,5244905000,2621250000,1428040000,741434000,382304000,67114000,47355000,29380000,14485000,13.08,10.40,8.63,9.29,158334000
3,31-12-2019,5467434000,2671908000,1562561000,746392000,418121000,67662000,51778000,31417000,16233000,13.22,10.51,8.18,9.07,167090000
4,31-03-2020,5767691000,2702776000,1723474000,793453000,483660000,69969000,58734000,34318000,19835000,13.09,10.40,8.05,8.94,182856000

In [26]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            21 non-null     object
 1   Global Revenue                  21 non-null     int64
 2   UCAN Streaming Revenue          21 non-null     int64
 3   EMEA Streaming Revenue          21 non-null     int64
 4   LATM Streaming Revenue          21 non-null     int64
 5   APAC Streaming Revenue          21 non-null     int64
 6   UCAN Members                    21 non-null     int64
 7   EMEA  Members                   21 non-null     int64
 8   LATM Members                    21 non-null     int64
 9   APAC Members                    21 non-null     int64
 10  UCAN ARPU                       21 non-null     float64
 11  EMEA ARPU                       21 non-null     float64
 12  LATM  ARPU                      21 non-null     float64
 13  APAC  ARPU                      21 non-null     float64
 14  Netflix Streaming Memberships   21 non-null     int64
dtypes: float64(4), int64(10), object(1)
memory usage: 2.6+ KB

In [27]:
data3.shape

(21, 15)

In [28]:
data3.isnull().sum()

Date                              0
Global Revenue                    0
UCAN Streaming Revenue            0
EMEA Streaming Revenue            0
LATM Streaming Revenue            0
APAC Streaming Revenue            0
UCAN Members                      0
EMEA  Members                     0
LATM Members                      0
APAC Members                      0
UCAN ARPU                         0
EMEA ARPU                         0
LATM  ARPU                        0
APAC  ARPU                        0
Netflix Streaming Memberships     0
dtype: int64

In [29]:
data3['Date']=pd.to_datetime(data3['Date'],format='%d-%m-%Y')

In [30]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            21 non-null     datetime64[ns]
 1   Global Revenue                  21 non-null     int64
 2   UCAN Streaming Revenue          21 non-null     int64
 3   EMEA Streaming Revenue          21 non-null     int64
 4   LATM Streaming Revenue          21 non-null     int64
 5   APAC Streaming Revenue          21 non-null     int64
 6   UCAN Members                    21 non-null     int64
 7   EMEA  Members                   21 non-null     int64
 8   LATM Members                    21 non-null     int64
 9   APAC Members                    21 non-null     int64
 10  UCAN ARPU                       21 non-null     float64
 11  EMEA ARPU                       21 non-null     float64
 12  LATM  ARPU                      21 non-null     float64
 13  APAC  ARPU                      21 non-null     float64
 14  Netflix Streaming Memberships   21 non-null     int64
dtypes: datetime64[ns](1), float64(4), int64(10)
memory usage: 2.6 KB

In [31]:
data3.columns

Index(['Date', 'Global Revenue', 'UCAN Streaming Revenue',
       'EMEA Streaming Revenue', 'LATM Streaming Revenue',
       'APAC Streaming Revenue', 'UCAN Members', 'EMEA  Members',
       'LATM Members', 'APAC Members', 'UCAN ARPU', 'EMEA ARPU', 'LATM  ARPU',
       'APAC  ARPU', 'Netflix Streaming Memberships '],
      dtype='object')

In [32]:
rename_columns = {
    'UCAN Streaming Revenue': 'Revenue_US_Canada',
    'EMEA Streaming Revenue': 'Revenue_Europe_MiddleEast_Africa',
    'LATM Streaming Revenue': 'Revenue_LatinAmerica',
    'APAC Streaming Revenue': 'Revenue_AsiaPacific',
    'UCAN Members': 'Subscribers_US_Canada',
    'EMEA  Members': 'Subscribers_Europe_MiddleEast_Africa',
    'LATM Members': 'Subscribers_LatinAmerica',
    'APAC Members': 'Subscribers_AsiaPacific',
    'UCAN ARPU': 'ARPU_US_Canada',
    'EMEA ARPU': 'ARPU_Europe_MiddleEast_Africa',
    'LATM  ARPU': 'ARPU_LatinAmerica',
    'APAC  ARPU': 'ARPU_AsiaPacific',
}

In [33]:
data3.rename(columns=rename_columns, inplace=True)
data3.head()

,Date,Global Revenue,Revenue_US_Canada,Revenue_Europe_MiddleEast_Africa,Revenue_LatinAmerica,Revenue_AsiaPacific,Subscribers_US_Canada,Subscribers_Europe_MiddleEast_Africa,Subscribers_LatinAmerica,Subscribers_AsiaPacific,ARPU_US_Canada,ARPU_Europe_MiddleEast_Africa,ARPU_LatinAmerica,ARPU_AsiaPacific,Netflix Streaming Memberships
0,2019-03-31,4520992000,2256851000,1233379000,630472000,319602000,66633000,42542000,27547000,12141000,11.45,10.23,7.84,9.37,148863000
1,2019-06-30,4923116000,2501199000,1319087000,677136000,349494000,66501000,44229000,27890000,12942000,12.52,10.13,8.14,9.29,151562000
2,2019-09-30,5244905000,2621250000,1428040000,741434000,382304000,67114000,47355000,29380000,14485000,13.08,10.40,8.63,9.29,158334000
3,2019-12-31,5467434000,2671908000,1562561000,746392000,418121000,67662000,51778000,31417000,16233000,13.22,10.51,8.18,9.07,167090000
4,2020-03-31,5767691000,2702776000,1723474000,793453000,483660000,69969000,58734000,34318000,19835000,13.09,10.40,8.05,8.94,182856000

In [34]:
data3.to_csv("Netflix Sub and Revnue overtime [Cleaned].csv", index=False)

**Dataset 4 = Netflix veiwing activity and watchlog**

**there are 5 sub csv**

In [35]:
data4_1=pd.read_csv("Netflix Viewing Activity  Watch Log/All_Clickstream.csv")
data4_2=pd.read_csv("Netflix Viewing Activity  Watch Log/All_Devices.csv")
data4_3=pd.read_csv("Netflix Viewing Activity  Watch Log/All_Profiles.csv")
data4_4=pd.read_csv("Netflix Viewing Activity  Watch Log/All_SearchHistory.csv")
data4_5=pd.read_csv("Netflix Viewing Activity  Watch Log/All_ViewingActivity.csv")

In [36]:
data4_1.head()

,Profile Name,Source,Navigation Level,Referrer Url,Webpage Url,Click Utc Ts
0,User 4,Source 0,signupPrompt,NaN,NaN,2022-10-08 14:04:47
1,User 4,Source 0,browseTitles,NaN,NaN,2022-10-08 14:04:46
2,User 4,Source 1,movieDetails,NaN,NaN,2022-09-30 14:53:50
3,User 4,Source 1,browseTitles,NaN,NaN,2022-09-30 14:53:50
4,User 4,Source 1,movieDetails,NaN,NaN,2022-09-30 14:53:49

In [37]:
data4_2['Profile Name'].nunique()

9

In [38]:
data4_2.head()

,Profile Name,Esn,Device Type,Acct First Playback Date,Acct Last Playback Date,Acct First Playback Date For User Generated Plays,Acct Last Playback Date For User Generated Plays,Profile First Playback Date,Profile Last Playback Date,Profile First Playback Date For User Generated Plays,Profile Last Playback Date For User Generated Plays,Deactivation Time
0,User 3,Esn 1,Device Type 4,2022-04-01T09:32:16.028Z,2022-11-07T12:57:43.624Z,2022-04-01T09:32:16.028Z,2022-11-07T12:57:43.624Z,2022-04-01T09:32:16.028Z,2022-11-07T12:57:43.624Z,2022-04-01T09:32:16.028Z,2022-11-07T12:57:43.624Z,NaN
1,User 1,Esn 6,Device Type 0,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,NaN,NaN,NaN,NaN,NaN
2,User 2,Esn 6,Device Type 0,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,NaN,NaN,NaN,NaN,NaN
3,User 3,Esn 6,Device Type 0,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,NaN,NaN,NaN,NaN,NaN
4,User 0,Esn 6,Device Type 0,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,2021-12-24T14:40:29.147Z,2022-10-06T17:29:04.497Z,2022-08-03T16:57:01.297Z,2022-10-06T17:29:04.497Z,2022-08-03T16:57:01.297Z,2022-10-06T17:29:04.497Z,NaN

In [39]:
data4_3.head()

,Profile Name,Game Handle,Profile Creation Time,Maturity Level,Primary Lang,Has Auto Playback,Max Stream Quality,Profile Lock Enabled,Profile Transferred,Profile Transfer Time,Profile Transferred From Account,Profile Transferred To Account,Date Of Birth,Gender,Opt-Out,Privacy And Data Settings
0,User 0,NaN,29-10-2021 05:42,ADULTS,en-IN,1.0,Unknown,False,False,NaN,NaN,NaN,NaN,NaN,{},NaN
1,User 1,NaN,29-10-2021 05:42,ADULTS,en-IN,1.0,Unknown,False,False,NaN,NaN,NaN,NaN,NaN,{},NaN
2,User 2,NaN,29-10-2021 05:42,ADULTS,en-IN,1.0,Unknown,False,False,NaN,NaN,NaN,NaN,NaN,{},NaN
3,User 3,NaN,29-10-2021 05:42,ADULTS,en-IN,1.0,Unknown,False,False,NaN,NaN,NaN,NaN,NaN,{},NaN
4,User 4,NaN,29-10-2021 05:19,ADULTS,en-IN,NaN,Unknown,False,False,NaN,NaN,NaN,NaN,NaN,{},NaN

In [40]:
data4_4.head()

,Profile Name,Country Iso Code,Device,Is Kids,Query Typed,Displayed Name,Action,Section,Utc Timestamp
0,User 4,AE,Device 0,0,NaN,"Manifest: Season 1: ""Pilot""",play,prequery_results,2022-08-01 13:59:19
1,User 4,AE,Device 0,0,NaN,NaN,select,prequery_results,2022-08-01 13:59:18
2,User 4,AE,Device 0,0,NaN,"Manifest: Season 1: ""Pilot""",play,prequery_results,2022-08-01 13:59:07
3,User 4,AE,Device 0,0,NaN,NaN,select,prequery_results,2022-08-01 13:59:03
4,User 4,AE,Device 0,0,the gray,The Gray Man,add,title_results,2022-07-17 13:59:23

In [41]:
data4_5.head()

,Profile Name,Start Time,Duration,Attributes,Title,Supplemental Video Type,Device Type,Bookmark,Latest Bookmark,Country
0,User 1,2022-04-28 16:08:56,00:00:06,NaN,Chernobyl 1986,NaN,Device Type 1,01:02:16,01:02:16,IN (India)
1,User 1,2022-04-28 15:54:30,00:09:39,NaN,13 Hours: The Secret Soldiers of Benghazi,NaN,Device Type 1,02:13:19,02:13:19,IN (India)
2,User 1,2022-04-28 15:53:20,00:00:06,NaN,Saving Private Ryan,NaN,Device Type 1,01:16:17,01:16:17,IN (India)
3,User 1,2022-04-28 15:52:18,00:00:15,NaN,Mosul,NaN,Device Type 1,01:06:44,01:06:44,IN (India)
4,User 1,2022-04-28 15:49:11,00:01:45,NaN,12 Strong,NaN,Device Type 1,00:52:28,00:52:28,IN (India)

**data4_1 Cleaning**

In [42]:
data4_1.isnull().sum()
data4_1.shape

(12104, 6)

In [43]:
data4_1=data4_1.drop(['Referrer Url','Webpage Url','Navigation Level'], axis=1)

In [44]:
data4_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12104 entries, 0 to 12103
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Profile Name  12104 non-null  object
 1   Source        12104 non-null  object
 2   Click Utc Ts  12104 non-null  object
dtypes: object(3)
memory usage: 283.8+ KB

In [45]:
data4_1['Click Utc Ts']=pd.to_datetime(data4_1['Click Utc Ts'])

**data4_2 cleaning**

In [46]:
data4_2.isnull().sum()

Profile Name                                             0
Esn                                                      0
Device Type                                              0
Acct First Playback Date                                17
Acct Last Playback Date                                 17
Acct First Playback Date For User Generated Plays       23
Acct Last Playback Date For User Generated Plays        23
Profile First Playback Date                             43
Profile Last Playback Date                              43
Profile First Playback Date For User Generated Plays    45
Profile Last Playback Date For User Generated Plays     45
Deactivation Time                                       83
dtype: int64

In [47]:
data4_2.shape

(137, 12)

In [48]:
data4_2.columns

Index(['Profile Name', 'Esn', 'Device Type', 'Acct First Playback Date',
       'Acct Last Playback Date',
       'Acct First Playback Date For User Generated Plays',
       'Acct Last Playback Date For User Generated Plays',
       'Profile First Playback Date', 'Profile Last Playback Date',
       'Profile First Playback Date For User Generated Plays',
       'Profile Last Playback Date For User Generated Plays',
       'Deactivation Time'],
      dtype='object')

In [49]:
col=['Profile Name','Device Type']
for i in col:
    data4_2=data4_2[col]

In [50]:
data4_2.isnull().sum()

Profile Name    0
Device Type     0
dtype: int64

**data4_3 cleaning**

In [51]:
data4_3.columns

Index(['Profile Name', 'Game Handle', 'Profile Creation Time',
       'Maturity Level', 'Primary Lang', 'Has Auto Playback',
       'Max Stream Quality', 'Profile Lock Enabled', 'Profile Transferred',
       'Profile Transfer Time', 'Profile Transferred From Account',
       'Profile Transferred To Account', 'Date Of Birth', 'Gender', 'Opt-Out',
       'Privacy And Data Settings'],
      dtype='object')

In [52]:
data4_3.isnull().sum()

Profile Name                        0
Game Handle                         9
Profile Creation Time               0
Maturity Level                      0
Primary Lang                        0
Has Auto Playback                   2
Max Stream Quality                  0
Profile Lock Enabled                0
Profile Transferred                 0
Profile Transfer Time               9
Profile Transferred From Account    9
Profile Transferred To Account      9
Date Of Birth                       9
Gender                              9
Opt-Out                             4
Privacy And Data Settings           5
dtype: int64

In [53]:
data4_3.shape

(9, 16)

In [54]:
col=['Profile Name','Profile Creation Time','Maturity Level']
for i in col:
    data4_3=data4_3[col]

In [55]:
data4_3.head()

  Profile Name Profile Creation Time Maturity Level
0       User 0      29-10-2021 05:42         ADULTS
1       User 1      29-10-2021 05:42         ADULTS
2       User 2      29-10-2021 05:42         ADULTS
3       User 3      29-10-2021 05:42         ADULTS
4       User 4      29-10-2021 05:19         ADULTS

**data_4_4 cleaning**

In [56]:
data4_4.shape

(2616, 9)

In [57]:
data4_4.isnull().sum()

Profile Name          0
Country Iso Code      0
Device                0
Is Kids               0
Query Typed         727
Displayed Name      818
Action                0
Section               0
Utc Timestamp         0
dtype: int64

In [58]:
data4_4.columns

Index(['Profile Name', 'Country Iso Code', 'Device', 'Is Kids', 'Query Typed',
       'Displayed Name', 'Action', 'Section', 'Utc Timestamp'],
      dtype='object')

In [59]:
col=['Displayed Name','Section']
data4_4=data4_4.drop(col,axis=1)
data4_4=data4_4.dropna(subset='Query Typed')

In [60]:
data4_4.shape

(1889, 7)

**data4_5 cleaning**

In [61]:
data4_5.shape

(9992, 10)

In [62]:
data4_5.isnull().sum()

Profile Name                  0
Start Time                    0
Duration                      0
Attributes                 8593
Title                         0
Supplemental Video Type    8147
Device Type                   0
Bookmark                      0
Latest Bookmark               0
Country                       0
dtype: int64

In [63]:
col=['Attributes','Supplemental Video Type','Bookmark','Latest Bookmark']
data4_5=data4_5.drop(col,axis=1)

In [64]:
data4_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9992 entries, 0 to 9991
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Profile Name  9992 non-null   object
 1   Start Time    9992 non-null   object
 2   Duration      9992 non-null   object
 3   Title         9992 non-null   object
 4   Device Type   9992 non-null   object
 5   Country       9992 non-null   object
dtypes: object(6)
memory usage: 468.5+ KB

In [65]:
data4_5.head()

,Profile Name,Start Time,Duration,Title,Device Type,Country
0,User 1,2022-04-28 16:08:56,00:00:06,Chernobyl 1986,Device Type 1,IN (India)
1,User 1,2022-04-28 15:54:30,00:09:39,13 Hours: The Secret Soldiers of Benghazi,Device Type 1,IN (India)
2,User 1,2022-04-28 15:53:20,00:00:06,Saving Private Ryan,Device Type 1,IN (India)
3,User 1,2022-04-28 15:52:18,00:00:15,Mosul,Device Type 1,IN (India)
4,User 1,2022-04-28 15:49:11,00:01:45,12 Strong,Device Type 1,IN (India)

In [66]:
data4_5['Start Time']=pd.to_datetime(data4_5['Start Time'])
data4_5['Duration']=pd.to_datetime(data4_5['Duration'])

C:\Users\dhruv\AppData\Local\Temp\ipykernel_10516\3806902326.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data4_5['Duration']=pd.to_datetime(data4_5['Duration'])

**merging**

**merge only 1 and 2 rest all are useless**

In [67]:
# Merge profile info
data_4 = pd.merge(data4_1, data4_2, on='Profile Name', how='inner')

In [68]:
data_4

       Profile Name    Source        Click Utc Ts    Device Type
0            User 4  Source 0 2022-10-08 14:04:47  Device Type 5
1            User 4  Source 0 2022-10-08 14:04:47  Device Type 1
2            User 4  Source 0 2022-10-08 14:04:47  Device Type 4
3            User 4  Source 0 2022-10-08 14:04:47  Device Type 2
4            User 4  Source 0 2022-10-08 14:04:47  Device Type 2
...             ...       ...                 ...            ...
237945       User 8  Source 0 2023-02-20 03:44:47  Device Type 0
237946       User 8  Source 0 2023-02-20 03:44:47  Device Type 1
237947       User 8  Source 0 2023-02-20 03:44:47  Device Type 3
237948       User 8  Source 0 2023-02-20 03:44:47  Device Type 3
237949       User 8  Source 0 2023-02-20 03:44:47  Device Type 8

[237950 rows x 4 columns]

In [69]:
data_4.isnull().sum()

Profile Name    0
Source          0
Click Utc Ts    0
Device Type     0
dtype: int64

In [70]:
data4_3.head()

  Profile Name Profile Creation Time Maturity Level
0       User 0      29-10-2021 05:42         ADULTS
1       User 1      29-10-2021 05:42         ADULTS
2       User 2      29-10-2021 05:42         ADULTS
3       User 3      29-10-2021 05:42         ADULTS
4       User 4      29-10-2021 05:19         ADULTS

In [71]:
data4_4.head()

,Profile Name,Country Iso Code,Device,Is Kids,Query Typed,Action,Utc Timestamp
4,User 4,AE,Device 0,0,the gray,add,2022-07-17 13:59:23
5,User 4,AE,Device 0,0,the gray,select,2022-07-17 13:59:17
11,User 4,AE,Device 0,0,stra,play,2022-07-01 14:28:04
12,User 4,AE,Device 0,0,stra,play,2022-07-01 14:13:00
13,User 4,AE,Device 0,0,stra,play,2022-07-01 14:10:08

In [72]:
data4_5.head()

,Profile Name,Start Time,Duration,Title,Device Type,Country
0,User 1,2022-04-28 16:08:56,2025-06-19 00:00:06,Chernobyl 1986,Device Type 1,IN (India)
1,User 1,2022-04-28 15:54:30,2025-06-19 00:09:39,13 Hours: The Secret Soldiers of Benghazi,Device Type 1,IN (India)
2,User 1,2022-04-28 15:53:20,2025-06-19 00:00:06,Saving Private Ryan,Device Type 1,IN (India)
3,User 1,2022-04-28 15:52:18,2025-06-19 00:00:15,Mosul,Device Type 1,IN (India)
4,User 1,2022-04-28 15:49:11,2025-06-19 00:01:45,12 Strong,Device Type 1,IN (India)

In [73]:
data_4.to_csv("Netiflix viewing.csv",index=False)
data4_5.to_csv("Netflix_viewing titles.csv",index=False)

**dataset 5=. Netflix Titles + IMDb Ratings (Merged)**

In [123]:
data5_credits=pd.read_csv("credits.csv")
data5_titles=pd.read_csv("titles.csv")

In [124]:
data5_credits.head()

   person_id       id             name                character   role
0       3748  tm84618   Robert De Niro            Travis Bickle  ACTOR
1      14658  tm84618     Jodie Foster            Iris Steensma  ACTOR
2       7064  tm84618    Albert Brooks                      Tom  ACTOR
3       3739  tm84618    Harvey Keitel  Matthew 'Sport' Higgins  ACTOR
4      48933  tm84618  Cybill Shepherd                    Betsy  ACTOR

In [125]:
data5_titles.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600

In [126]:
print(f"Columns of credits:{data5_credits.columns}\n Columns of titles:{data5_titles.columns}")

Columns of credits:Index(['person_id', 'id', 'name', 'character', 'role'], dtype='object')
 Columns of titles:Index(['id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'seasons', 'imdb_id', 'imdb_score', 'imdb_votes', 'tmdb_popularity',
       'tmdb_score'],
      dtype='object')

In [127]:
data5_credits=data5_credits.drop(['person_id'], axis=1)
data5_titles=data5_titles.drop(['description','imdb_id','imdb_votes','tmdb_popularity','tmdb_score','seasons'],axis=1)

In [128]:
data5_credits.shape

(77801, 4)

In [129]:
data5_titles.shape

(5850, 9)

In [130]:
data5_credits.isnull().sum()

id              0
name            0
character    9772
role            0
dtype: int64

In [131]:
data5_credits=data5_credits.dropna(subset='character')

In [132]:
data5_titles.isnull().sum()

id                         0
title                      1
type                       0
release_year               0
age_certification       2619
runtime                    0
genres                     0
production_countries       0
imdb_score               482
dtype: int64

In [133]:
data5_titles=data5_titles.dropna(subset='imdb_score')

In [134]:
data5_titles['age_certification']=data5_titles['age_certification'].fillna('Not Availavle')

In [135]:
IMBD = data5_titles.merge(data5_credits, on='id', how='left')

In [139]:
IMBD.isnull().sum()

id                        0
title                     0
type                      0
release_year              0
age_certification         0
runtime                   0
genres                    0
production_countries      0
imdb_score                0
name                    735
character               735
role                    735
dtype: int64

In [142]:
IMBD.head()

,id,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_score
0,tm84618,Taxi Driver,MOVIE,1976,R,114,"['drama', 'crime']",['US'],8.2
1,tm84618,Taxi Driver,MOVIE,1976,R,114,"['drama', 'crime']",['US'],8.2
2,tm84618,Taxi Driver,MOVIE,1976,R,114,"['drama', 'crime']",['US'],8.2
3,tm84618,Taxi Driver,MOVIE,1976,R,114,"['drama', 'crime']",['US'],8.2
4,tm84618,Taxi Driver,MOVIE,1976,R,114,"['drama', 'crime']",['US'],8.2

In [141]:
IMBD=IMBD.drop(['role','name','character'],axis=1)

In [147]:
final=IMBD.drop_duplicates()
final.shape

(5368, 9)

In [148]:
final.to_csv("Netflix IMBD.csv", index=False)